import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Betting Platform",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className="bg-[#030C16]">
          <Navbar />
          <SidebarProvider>
            <div className="flex">
              <AppSidebar />
              <SidebarTrigger className="text-white"></SidebarTrigger>   
            </div>
            <main className="flex-1 p-6">{children}</main>
            
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
